use 4 whitespace instead of 3 in configs/scripts
    after commit aeaef6d I seem to like 4 whitespaces more than 3

diff --git a/bin/find-parent-dir b/bin/find-parent-dir
--- a/bin/find-parent-dir
+++ b/bin/find-parent-dir
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 
 if [ $BASH_SOURCE == $0 ]; then
-   echo "Don't call directly (./find-parent-dir), use source instead (. find-parent-dir)"
+    echo "Don't call directly (./find-parent-dir), use source instead (. find-parent-dir)"
 
-   exit 1
+    exit 1
 fi
 
 if [ $# == 0 ]; then
-   echo "Usage: . find-parent-dir <parent-dir-name> [count]"
-   return 1
+    echo "Usage: . find-parent-dir <parent-dir-name> [count]"
+    return 1
 fi
 
 fpd_count=${2:-"1"}
@@ -17,29 +17,29 @@ fpd_cur_full_path=$fpd_start_dir
 fpd_wanted_dir=$1
 
 echo "$fpd_count" | grep -q "^[0-9]\+$" || {
-   echo "Usage: . find-parent-dir <parent-dir-name> [count]"
-   return 1
+    echo "Usage: . find-parent-dir <parent-dir-name> [count]"
+    return 1
 }
 
 while [ "$fpd_cur_full_path" != "/" ]
 do
-   fpd_cur_dir=$(basename "$fpd_cur_full_path")
+    fpd_cur_dir=$(basename "$fpd_cur_full_path")
 
-   if [ "${fpd_cur_dir}" == "${fpd_wanted_dir}" ]; then
-      fpd_count=$(($fpd_count - 1))
+    if [ "${fpd_cur_dir}" == "${fpd_wanted_dir}" ]; then
+        fpd_count=$(($fpd_count - 1))
 
-      if [ $fpd_count == 0 ]; then
-         cd "$fpd_cur_full_path"
-         return 0
-      fi
-   fi
+        if [ $fpd_count == 0 ]; then
+            cd "$fpd_cur_full_path"
+            return 0
+        fi
+    fi
 
-   fpd_cur_full_path=$(dirname "$fpd_cur_full_path")
+    fpd_cur_full_path=$(dirname "$fpd_cur_full_path")
 done
 
 if [ "$fpd_cur_full_path" != "$fpd_wanted_dir" ]; then
-   echo "Parent directory '$fpd_wanted_dir' not found."
-   return 1
+    echo "Parent directory '$fpd_wanted_dir' not found."
+    return 1
 fi
 
 return 0
